language: android
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - lib32z1
    - zip
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_2f2170bdfc25_key -iv $encrypted_2f2170bdfc25_iv
  -in signing.tar.enc -out signing.tar -d
- yes | sdkmanager "platforms;android-27"
- wget -q https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
  -O ndk.zip
- unzip -q ndk.zip
- export ANDROID_NDK_HOME=`pwd`/android-ndk-r16b
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
- tar xvf signing.tar
script:
- chmod +x gradlew
- ./gradlew assembleRelease
- ./gradlew testRelease
before_deploy:
  - zip -jr mapping.zip App/build/outputs/mapping
deploy:
  - provider: script
    skip_cleanup: 'true'
    script: ./gradlew bintrayUpload
    on:
      tags: true
      repo: alanwoolley/innoextract-android
  - provider: releases
    skip_cleanup: 'true'
    api_key:
      secure: IQZ419yGt7iGUmBSgGl8ah3ZXJw005uoPlEqlNelFsqAImsUgEXsJFORg+Jo8l/Lyfi3H1hDCn5IM/KTOsUuAIabMctOSP99AyIK8AzNbnLQbU57lvZwfAnxFBn024ir7pYXw/MIoheWnR3RJs+ATiP301HLaWpdxTEhcsDn2n8=
    file_glob: true
    file:
      - App/build/outputs/apk/release/*.apk
      - mapping.zip
      - Service/build/outputs/aar/*.aar
    on:
      tags: true
      repo: alanwoolley/innoextract-android


